### ISSUE TITLE
Should Shovill support SE reads?

### ISSUE THREAD

**Issue by lindechun** [tseemann/shovill#58] opened 2018-03-24 10:44 UTC
Should Shovill support SE reads?

**Comment by lindechun** [comment] 2018-03-24 10:44
Should Shovill support SE reads?

**Comment by tseemann** [comment] 2018-03-24 10:45
Do you have single-end Illumina reads for a whole genome sequencing project?

**Comment by lindechun** [comment] 2018-03-24 10:55
nope. but i have some single-end BGISeq-500 reads.

**Comment by tseemann** [comment] 2018-04-16 11:36
Nice!   

This is a duplicate of #43 so I'll close this and leave the original open.

**Closed by tseemann** 2018-04-16 11:36 UTC
Labels: enhancement
